# Application name
spring.application.name=smartwash

# H2 in-memory database configuration
spring.datasource.url=jdbc:h2:mem:smartwashdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Enable H2 console so you can see your database in the browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
