# Application name
spring.application.name=smartwash

# H2 Database
spring.datasource.url=jdbc:h2:mem:smartwashdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# TTN MQTT Configuration
mqtt.broker.url=tcp://eu1.cloud.thethings.network:1883
mqtt.client.id=smartwash-backend
mqtt.username=smartwash-cameroon@ttn
mqtt.password=NNSXS.ZVLBYOYKJCKSYLYTB4TCUIN5UVLU3BXGMACTPGQ.JE6DEGGMMD4EIUGBSLCH2TR3F4AKQLBI6PR4FGOULCU5RARX27FQ
mqtt.topic.uplink=v3/smartwash-cameroon@ttn/devices/+/up

# Africa's Talking SMS Configuration
africastalking.username=sandbox
africastalking.apikey=atsk_8c8706cdcd14c1237799075c13a3b779b485aa7402da1e1b8db370fd943a8df1b2fc8c6f
africastalking.senderid=SmartWASH

# Phone numbers to alert ? comma separated
# Use international format with country code
# Cameroon country code is +237
smartwash.alert.phonenumbers=+237650000001,+237650000002
smartwash.alert.waterlevel.threshold=25.0



